### ISSUE TITLE
Crashing in Android 14

### ISSUE THREAD

**Issue by iamNormi** [egorolegovichyakovlev/DroidRec#13] opened 2023-10-20 14:02 UTC
When start recording the app got crashed. I'm in Android 14 Graphene OS. The app totally ok when i am on Android 13 , The crashing happening after i updated to Android 14

**Comment by egorolegovichyakovlev** [comment] 2023-10-20 15:31
Is it solved? Could you specify any details about the crash?

**Comment by iamNormi** [comment] 2023-10-20 20:47
No, it not solved I closed it for a TYPO.

**Comment by iamNormi** [comment] 2023-10-20 20:54
> Is it solved? Could you specify any details about the crash?

Details:
Pixel 6a with graphene OS.
Needed permissions are given.
Tried re-installing app.
Nothing solved..

This problem only on Android 14. Before Updating i Using it Android 13, worked just fine.

I hope you will fix this issue.

**Comment by astrophilehuwan** [comment] 2024-01-07 07:51
Same, having issues running it on OneUI 6.0 on Android 14

**Comment by egorolegovichyakovlev** [comment] 2024-01-26 21:16
Duplicate of #14

**Closed by egorolegovichyakovlev** 2024-01-26 21:16 UTC
